package pagamento.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import java.util.ArrayList;
import java.util.List;
import pagamento.model.Colaborador;
import pagamento.repositories.ColaboradorRepository;

@RestController    // This means that this class is a Controller
@RequestMapping(path="/colaborador") // This means URL's start with /demo (after Application path)
public class ColaboradorController {
	
	
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private ColaboradorRepository colaboradorRepository;
	

	@PostMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser ( @RequestParam String nome, @RequestParam String endereco,
			@RequestParam String telefone, @RequestParam String bairro, @RequestParam String cep, @RequestParam String cpf,
			@RequestParam float salarioAtual) {
		
		Colaborador c = new Colaborador();
		c.setBairro(bairro);
		c.setCep(cep);
		c.setCpf(cpf);
		c.setEndereco(endereco);
		c.setNome(nome);
		c.setSalarioAtual(salarioAtual);
		c.setTelefone(telefone);
		
		
		
		
		colaboradorRepository.save(c);
		return "Salvo";
	}
	@DeleteMapping(path="/delete") // Map ONLY GET Requests
	public @ResponseBody String deleteById ( @RequestParam int codigo) {
		try {
			Colaborador c = new Colaborador(codigo);
			colaboradorRepository.delete(c);
			}
		catch (Exception ex) {
		      return "Error deleting the user:" + ex.toString();
		    }
		    return "Colaborador de codigo: "+codigo+" foi deletado com sucesso";	
	}
	
	
	@PutMapping(path ="/update")
	public @ResponseBody void update (@RequestParam int code ,@RequestParam String nome, @RequestParam String endereco,
			@RequestParam String telefone, @RequestParam String bairro, @RequestParam String cep, @RequestParam String cpf,
			@RequestParam float salarioAtual) {
		 Colaborador c = new Colaborador(code);
		 
		 
		
	}
	
	
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<Colaborador> getAllUsers() {
		return colaboradorRepository.findAll();
	}
	

}
